### ISSUE TITLE
Server failing to start 

### ISSUE THREAD

**Issue by Kizwiz** [ProjectEssentials/ProjectEssentials-Cooldown#5]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 3/22/20 9:26 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.server.MinecraftServer.getCommandManager()Lnet/minecraft/command/Commands;
	at com.mairwunnx.projectessentials.cooldown.EntryPoint.onServerStarting(EntryPoint.kt:64) ~[?:1.15.2-1.0.1] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_135_EntryPoint_onServerStarting_FMLServerStartingEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.server.ServerLifecycleHooks.handleServerStarting(ServerLifecycleHooks.java:90) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:242) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world/MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 3.10.0-957.21.2.el7.x86_64
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2880704288 bytes (2747 MB) / 4105699328 bytes (3915 MB) up to 4105699328 bytes (3915 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xmx4096M -Xms4096M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge_server.1.15.2-31.1.24.jar object_holder_definalize PLUGINSERVICE 
		/forge_server.1.15.2-31.1.24.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge_server.1.15.2-31.1.24.jar capability_inject_definalize PLUGINSERVICE 
		/forge_server.1.15.2-31.1.24.jar runtimedistcleaner PLUGINSERVICE 
		/forge_server.1.15.2-31.1.24.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.2.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.2.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.24
	FML Language Providers: 
		javafml@31.1
		minecraft@1
		kotlinfml@1.5.0
	Mod List: 
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 DONE}
		SilentMechanisms-1.15.2-0.7.0+50.jar Silent's Mechanisms {silents_mechanisms@0.7.0+50 DONE}
		KleeSlabs_1.15.2-8.0.0.jar KleeSlabs {kleeslabs@8.0.0 DONE}
		essentials-1.15.2-2.7.0.jar Essentials {essentials@1.15.2-2.7.0 DONE}
		BetterTitleScreen-1.15.2-1.9.jar Better Title Screen {bettertitlescreen@1.15.2-1.9 DONE}
		XaerosWorldMap_1.5.5_Forge_1.15.2.jar Xaero's World Map {xaeroworldmap@1.5.5 DONE}
		Controlling-6.1.1.jar Controlling {controlling@6.1.1 DONE}
		ReAuth-1.14-3.8.0.jar ReAuth {reauth@3.8.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		globaldatapack-1.15.2-1.3.jar Dark Roleplay - Global Datapacks {globaldatapack@1.15.2-0.1.0 DONE}
		Powah-1.15.2-1.1.7.jar Powah {powah@1.1.7 DONE}
		ftb-gui-library-1.0.0.14.jar FTB GUI Library {ftbguilibrary@1.0.0.14 DONE}
		Bookshelf-1.15.2-5.1.4.jar Bookshelf {bookshelf@5.1.4 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		randompatches-1.15.2-1.21.1.1.jar RandomPatches {randompatches@1.15.2-1.21.1.1 DONE}
		DarkUtilities-1.15.2-3.0.1.jar Dark Utilities {darkutils@3.0.1 DONE}
		Apotheosis-1.15.2-3.0.6.jar Apotheosis {apotheosis@3.0.6 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		MekanismGenerators-1.15.2-9.9.16.408.jar Mekanism: Generators {mekanismgenerators@9.9.16 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		refinedstorage-1.8.1.jar Refined Storage {refinedstorage@1.8.1 DONE}
		corpse-1.15.2-1.0.2.jar Corpse {corpse@1.15.2-1.0.2 DONE}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 DONE}
		lightestlampsmod-3.3.0.jar Lightest Lamps {lightestlamp@3.3.0 DONE}
		industrial-foregoing-1.15.2-2.2.2-28d4a81.jar Industrial Foregoing {industrialforegoing@2.2.2 DONE}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		embellishcraft-1.15.2-2.0.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.0.0.0 DONE}
		BiomesOPlenty-1.15.2-10.0.0.345-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.342 DONE}
		phosphor-mc1.15.2-forge-0.4.2-rc1.jar Phosphor {phosphor@0.4.2-rc1 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		valhelsia_structures-15.0.2.jar Valhelsia Structures {valhelsia_structures@15.0.2 DONE}
		Lollipop-1.15.2-1.0.9.jar Lollipop {lollipop@1.0.9 DONE}
		SilentGear-1.15.2-1.5.3+78.jar Silent Gear {silentgear@1.5.3+78 DONE}
		simplefarming-1.15.2-1.2.7.jar Simple Farming {simplefarming@1.15.2-1.2.7 DONE}
		SolarFluxReborn-1.15.2-15.0.0.jar Solar Flux Reborn {solarflux@15.0.0 DONE}
		curios-FORGE-1.15.2-2.0.1.jar Curios API {curios@FORGE-1.15.2-2.0.1 DONE}
		extlights-1.8.jar Extended Lights {extlights@1.8 DONE}
		ClothConfig2-2.0.jar Cloth Config Forge v2 API {cloth-config2@2.0 DONE}
		Project Essentials Cooldown-1.15.2-1.0.1.jar Project Essentials Cooldown {project_essentials_cooldown@1.15.2-1.0.1 DONE}
		Project Essentials Chat-1.15.2-1.1.1.jar Project Essentials Chat {project_essentials_chat@1.15.2-1.1.1 DONE}
		elevatorid-1.15.2-1.7.0.jar Elevator Mod {elevatorid@1.15.2-1.7.0 DONE}
		noRecipeBook_v1.5.2formc1.15.2.jar No Recipe Book {norecipebook@1.5.2 DONE}
		MekanismTools-1.15.2-9.9.16.408.jar Mekanism: Tools {mekanismtools@9.9.16 DONE}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 DONE}
		ChunkNoGoByeBye-1.15.2-1.2.0.jar ChunkNoGoByeBye {chunknogobyebye@1.15.2-1.2.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 DONE}
		cc-tweaked-1.15.2-1.86.2.jar CC: Tweaked {computercraft@1.86.2 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		mcw-furnitures-1.0.0-mc1.15.2.jar Macaw's Furniture {mcwfurnitures@1.0.0 DONE}
		cherishedworlds-FORGE-1.15.2-3.0.jar Cherished Worlds {cherishedworlds@FORGE-1.15.2-3.0 DONE}
		CustomWindowTitle-1.15.2-v1.0.0.jar Custom Window Title {customwindowtitle@1.0.0 DONE}
		Project Essentials Spawn-1.15.2-1.1.0.jar Project Essentials Spawn {project_essentials_spawn@1.15.2-1.1.0 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		TrashSlot_1.15.2-11.0.0.jar TrashSlot {trashslot@11.0.0 DONE}
		torchslabmod-1.15.1_v1.5.jar Torch Slab Mod {torchslabmod@1.5.0 DONE}
		EquipmentTooltips-1.15.2-1.4.0+11.jar Equipment Tooltips {equipmenttooltips@1.4.0+11 DONE}
		mining-helmet-1.15.2-1.0.7.jar Mining Helmet {mining_helmet@1.0.7 DONE}
		Project Essentials Backup-1.15.2-1.0.1.jar Project Essentials Backup {project_essentials_backup@1.15.2-1.0.1 DONE}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 DONE}
		buzzierbees-1.2.jar Buzzier Bees {buzzierbees@1.2 DONE}
		Mekanism-1.15.2-9.9.16.408.jar Mekanism {mekanism@9.9.16 DONE}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 DONE}
		reap-1.12.2.jar Reap Mod {reap@1.12.2 DONE}
		Waystones_1.15.2-6.0.0.jar Waystones {waystones@6.0.0 DONE}
		comforts-FORGE-1.15.2-2.0.jar Comforts {comforts@FORGE-1.15.2-2.0 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		FruitTrees-1.15.2-1.1.6.jar Fruit Trees {fruittrees@1.1.6 DONE}
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		SimpleStorageNetwork-1.15.2-0.2.4.jar Simple Storage Network {storagenetwork@1.15.2-0.2.4 DONE}
		SereneSeasons-1.15.2-3.0.0.68-universal.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.68 DONE}
		decorative_blocks_6c.jar Decorative Blocks {decorative_blocks@1.6 DONE}
		BotanyPots-1.15.2-2.0.1.jar BotanyPots {botanypots@2.0.1 DONE}
		mcjtylib-1.15-4.0.2-alpha.jar McJtyLib {mcjtylib@1.15-4.0.2-alpha DONE}
		rftoolsbase-1.15-1.0.0-alpha.jar RFToolsBase {rftoolsbase@1.15-1.0.0-alpha DONE}
		xnet-1.15-2.0.1-alpha.jar XNet {xnet@1.15-2.0.1-alpha DONE}
		rftoolsstorage-1.15-1.0.2-alpha.jar RFToolsStorage {rftoolsstorage@1.15-1.0.2-alpha DONE}
		mapperbase-1.15.2-1.0.0.0.jar Mapper Base {mapperbase@1.15.2-1.0.0.0 DONE}
		ToastControl-1.15.2-3.0.1.jar Toast Control {toastcontrol@3.0.1 DONE}
		immersive-portals-0.7(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.7 DONE}
		rftoolspower-1.15-2.0.1-alpha.jar RFToolsPower {rftoolspower@1.15-2.0.1-alpha DONE}
		extradisks-1.15.1-1.2.jar Extra Disks {extradisks@1.15.1-1.2 DONE}
		ftb-chunks-1.0.1.2.jar FTB Chunks {ftbchunks@1.0.1.2 DONE}
		forge-1.15.2-31.1.24-universal.jar Forge {forge@31.1.24 DONE}
		Bountiful-3.0.0-1.15.2.jar Bountiful {bountiful@3.0.0-1.15.2 DONE}
		Project Essentials Core-MOD-1.15.2-1.1.0.jar Project Essentials Core {project_essentials_core@1.15.2-1.1.0 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CraftingTweaks_1.15.1-11.0.0.jar Crafting Tweaks {craftingtweaks@11.0.0 DONE}
		forge-1.15.2-31.1.24-server.jar Minecraft {minecraft@1.15.2 DONE}
		cofh_core-1.15.2-0.3.2b.jar CoFH Core {cofh_core@0.3.2b DONE}
		ensorcellation-1.15.2-0.3.0b.jar Ensorcellation {ensorcellation@0.3.0b DONE}
		rftoolsutility-1.15-2.0.0-alpha.jar RFToolsUtility {rftoolsutility@1.15-2.0.0-alpha DONE}
		EnchantmentDescriptions-1.15.2-2.0.3.jar EnchantmentDescriptions {enchdesc@2.0.3 DONE}
		swingthroughgrass-1.15.2-1.4.0.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.0 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ToolBelt-1.15.2-1.14.1.jar Tool Belt {toolbelt@1.14.1 DONE}
		titanium-1.15.2-2.3.7.jar Titanium {titanium@2.3.7 DONE}
		SilentLib-1.15.2-4.6.0+48.jar Silent Lib {silentlib@4.6.0+48 DONE}
		forbidden_arcanus-1.15.2-1.2-beta-3.jar Forbidden & Arcanus {forbidden_arcanus@1.15.1-1.0-beta-1 DONE}
		archers_paradox-1.15.2-0.3.0b.jar Archer's Paradox {archers_paradox@0.3.0b DONE}
		rftoolsbuilder-1.15-2.0.0-alpha.jar RFToolsBuilder {rftoolsbuilder@1.15-2.0.0-alpha DONE}
		Project Essentials Warps-1.15.2-1.0.1.jar Project Essentials Warps {project_essentials_warps@1.15.2-1.0.1 DONE}
		Xaeros_Minimap_20.5.1_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.1 DONE}
		Project Essentials Permissions-1.15.2-1.0.2.jar Project Essentials Permissions {project_essentials_permissions@1.15.2-1.0.2 DONE}
		Project Essentials-1.15.2-1.1.2.jar Project Essentials {project_essentials@1.15.2-1.1.2 DONE}
		FastWorkbench-1.15.1-3.0.0.jar FastWorkbench {fastbench@3.0.0 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		DoubleSlabs-1.15-2.0.1.jar Double Slabs {doubleslabs@2.0.1 DONE}
		Project Essentials Home-1.15.2-1.1.0.jar Project Essentials Home {project_essentials_home@1.15.2-1.1.0 DONE}
		tubesreloaded-1.15.2-1.3.0c.jar Tubes Reloaded {tubesreloaded@1.15.2-1.3.0c DONE}
		structurize-0.10.281-ALPHA.jar Structurize {structurize@0.10.281-ALPHA DONE}
		minecolonies-0.10.768-ALPHA-universal.jar Minecolonies {minecolonies@0.10.768-ALPHA DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		Aquaculture-1.15.2-2.0.11.jar Aquaculture 2 {aquaculture@1.15.2-2.0.11 DONE}
		refinedstorageaddons-0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 DONE}
		CosmeticArmorReworked-1.15.2-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.15.2-v1a DONE}
		DefaultOptions_1.15.2-11.0.1.jar Default Options {defaultoptions@11.0.1 DONE}
	Kiwi Modules: 
		fruittrees:fruittrees
		fruittrees:hybridization
		kiwi:contributors
	Player Count: 0 / 20; []
	Data Packs: vanilla, mod:aiimprovements (incompatible), mod:apotheosis (incompatible), mod:appleskin (incompatible), mod:aquaculture, mod:archers_paradox (incompatible), mod:bettertitlescreen, mod:biomesoplenty, mod:blur (incompatible), mod:bookshelf (incompatible), mod:botanypots (incompatible), mod:bountiful (incompatible), mod:buzzierbees, mod:caelus (incompatible), mod:cfm (incompatible), mod:cherishedworlds (incompatible), mod:cloth-config2 (incompatible), mod:cofh_core (incompatible), mod:comforts (incompatible), mod:computercraft (incompatible), mod:controlling (incompatible), mod:corpse, mod:cosmeticarmorreworked (incompatible), mod:craftingtweaks (incompatible), mod:curios (incompatible), mod:curiouselytra (incompatible), mod:customwindowtitle, mod:darkutils (incompatible), mod:decorative_blocks, mod:defaultoptions (incompatible), mod:doggytalents (incompatible), mod:doubleslabs, mod:elevatorid, mod:embellishcraft (incompatible), mod:enchdesc (incompatible), mod:ensorcellation (incompatible), mod:equipmenttooltips (incompatible), mod:essentials (incompatible), mod:extlights (incompatible), mod:extradisks, mod:fastbench (incompatible), mod:fastfurnace (incompatible), mod:forbidden_arcanus (incompatible), mod:forge (incompatible), mod:fruittrees, mod:globaldatapack (incompatible), mod:immersive_portals (incompatible), mod:industrialforegoing (incompatible), mod:inventorysorter (incompatible), mod:ironchest, mod:jei (incompatible), mod:kiwi, mod:kleeslabs (incompatible), mod:lightestlamp, mod:lollipop (incompatible), mod:mapperbase, mod:mcjtylib (incompatible), mod:mcwbridges, mod:mcwfurnitures, mod:mcwroofs, mod:mcwwindows, mod:mekanism, mod:mekanismgenerators, mod:mekanismtools, mod:minecolonies (incompatible), mod:mining_helmet (incompatible), mod:morpheus (incompatible), mod:mousetweaks (incompatible), mod:naturescompass (incompatible), mod:netherportalfix (incompatible), mod:norecipebook, mod:phosphor, mod:placebo (incompatible), mod:powah (incompatible), mod:randompatches (incompatible), mod:reap, mod:reauth (incompatible), mod:refinedstorage (incompatible), mod:refinedstorageaddons (incompatible), mod:rftoolsbase (incompatible), mod:rftoolsbuilder (incompatible), mod:rftoolspower (incompatible), mod:rftoolsstorage (incompatible), mod:rftoolsutility (incompatible), mod:sereneseasons, mod:silentgear (incompatible), mod:silentlib (incompatible), mod:silents_mechanisms (incompatible), mod:simplefarming, mod:solarflux (incompatible), mod:storagedrawers (incompatible), mod:storagenetwork (incompatible), mod:structurize (incompatible), mod:swingthroughgrass (incompatible), mod:titanium (incompatible), mod:toastcontrol (incompatible), mod:toolbelt (incompatible), mod:torchmaster (incompatible), mod:torchslabmod, mod:trashslot (incompatible), mod:tubesreloaded (incompatible), mod:usefulbackpacks, mod:uteamcore, mod:valhelsia_structures (incompatible), mod:waila (incompatible), mod:waystones (incompatible), mod:xaerominimap, mod:xaeroworldmap, mod:xnet (incompatible), modpack:Valhelsia_CHUNKLOADER (incompatible), modpack:Valhelsia_RECIPE (incompatible), modpack:Valhelsia_SILENTGEAR (incompatible), mod:ftbchunks (incompatible), mod:ftbguilibrary (incompatible), mod:chunknogobyebye, mod:project_essentials, mod:project_essentials_backup, mod:project_essentials_chat, mod:project_essentials_cooldown, mod:project_essentials_core, mod:project_essentials_home, mod:project_essentials_permissions, mod:project_essentials_spawn, mod:project_essentials_warps
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MairwunNx** [comment]
### ✔ Thanks for reporting, @Kizwiz! Fixed in both minecraft versions (1.14.4 & 1.15.2).

**Comment by Kizwiz** [comment]
Wow that was quick, thanks 💃

**Comment by MairwunNx** [comment]
No problem! If you still getting this issue, please feedback. 🥰👍
